In [1]:
#Завдання 1
#Створіть одновимірний масив (вектор) зі збільшувальною арифметичною послідовністю, де кожне наступне число більше попереднього на 5, починаючи з 3, та виведіть його значення.
import numpy as np
start_value = 3
num_elements = 10
sequence = np.arange(start_value, start_value + num_elements * 5, 5)
print(sequence)


[ 3  8 13 18 23 28 33 38 43 48]


In [2]:
#Завдання 2
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками кожного числа та його попереднього, починаючи з 1, та виведіть його значення.
import numpy as np
n = 3
matrix = np.zeros((n, n))
current_value = 1
for i in range(n):
    for j in range(n):
        matrix[i][j] = current_value
        current_value *= (current_value + 1)
print(matrix)


[[1.00000000e+00 2.00000000e+00 6.00000000e+00]
 [4.20000000e+01 1.80600000e+03 3.26344200e+06]
 [1.06500570e+13 1.13423713e+26 1.28649387e+52]]


In [3]:
#Завдання 3
#Створіть масив розміром 8x8, заповніть його випадковими натуральними числами від 1 до 100 та знайдіть середнє арифметичне його елементів.
import numpy as np
n = 8
matrix = np.random.randint(1, 101, size=(n, n))
print("Матриця:")
print(matrix)
average = np.mean(matrix)
print(f"Середнє арифметичне елементів матриці: {average}")


Матриця:
[[99  6 27 41 73 97 87 83]
 [31  7 29 59 18 96 79 14]
 [23 30 51 57 65 49 32 98]
 [20 24  8 33 32 71 71 50]
 [95 51  2 33 60 17 72 16]
 [14 74 22 33 52 25 65 93]
 [72 22 38 49 80 56 92  4]
 [95 70 82 98 93 56  1 12]]
Середнє арифметичне елементів матриці: 50.0625


In [4]:
#Завдання 4
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.
import numpy as np
n = 4
matrix = np.random.rand(n, n)
print("Матриця:")
print(matrix)
count_above_0_5 = np.sum(matrix > 0.5)
print(f"Кількість елементів, більших за 0.5: {count_above_0_5}")


Матриця:
[[0.14210006 0.06847478 0.10900624 0.57212121]
 [0.8633222  0.04617326 0.22345677 0.72759769]
 [0.8000421  0.10110956 0.59010539 0.55485798]
 [0.16222038 0.86726897 0.27480226 0.81614908]]
Кількість елементів, більших за 0.5: 8


In [5]:
#Завдання 5
#Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами від -15 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np
n = 7
array1 = np.random.randint(-15, 16, size=n)
array2 = np.random.randint(-15, 16, size=n)
print("Перший масив:", array1)
print("Другий масив:", array2)
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)


Перший масив: [-10   2 -12  10   0  -8   2]
Другий масив: [  8 -11 -10  -9  11  13   8]
Результат додавання: [ -2  -9 -22   1  11   5  10]
Результат віднімання: [-18  13  -2  19 -11 -21  -6]
Результат множення: [ -80  -22  120  -90    0 -104   16]


In [6]:
#Завдання 6
#Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.
import numpy as np
n = 7
vector1 = np.random.randint(-10, 11, size=n)
vector2 = np.random.randint(-10, 11, size=n)
print("Перший вектор:", vector1)
print("Другий вектор:", vector2)
dot_product = np.dot(vector1, vector2)
print("Скалярний добуток:", dot_product)


Перший вектор: [ 8  4  3 -5  7 -1 -6]
Другий вектор: [  1 -10   5 -10   0  -8   4]
Скалярний добуток: 17


In [7]:
#Завдання 7
#Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою.
import numpy as np
m1, n1 = 4, 2
m2, n2 = 2, 5
matrix1 = np.random.randint(1, 13, size=(m1, n1))
matrix2 = np.random.randint(1, 13, size=(m2, n2))
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)
result_matrix = np.dot(matrix1, matrix2)
print("Результат перемноження матриць:")
print(result_matrix)


Перша матриця:
[[ 9  1]
 [11  9]
 [12  2]
 [ 1 10]]
Друга матриця:
[[ 5  5 12  3  2]
 [ 9  9  6  1  9]]
Результат перемноження матриць:
[[ 54  54 114  28  27]
 [136 136 186  42 103]
 [ 78  78 156  38  42]
 [ 95  95  72  13  92]]


In [8]:
#Завдання 8
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
import numpy as np
n = 2
matrix = np.random.randint(1, 13, size=(n, n))
print("Матриця:")
print(matrix)
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Ця матриця не має оберненої матриці, оскільки вона є сингулярною.")


Матриця:
[[10  4]
 [ 8  4]]
Обернена матриця:
[[ 0.5  -0.5 ]
 [-1.    1.25]]


In [9]:
#Завдання 9
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np
n = 3
matrix = np.random.rand(n, n)
print("Початкова матриця:")
print(matrix)
transposed_matrix = np.transpose(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[0.19574336 0.17118037 0.15354335]
 [0.21687254 0.50748869 0.5452408 ]
 [0.78251162 0.24518753 0.31514828]]
Транспонована матриця:
[[0.19574336 0.21687254 0.78251162]
 [0.17118037 0.50748869 0.24518753]
 [0.15354335 0.5452408  0.31514828]]


In [10]:
#Завдання 10
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю.
import numpy as np
m, n = 3, 4
matrix = np.random.rand(m, n)
vector = np.random.rand(n)
print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
result = np.dot(matrix, vector)
print("Добуток вектора на матрицю:")
print(result)


Матриця:
[[0.71569774 0.11841384 0.68015717 0.07989155]
 [0.4348733  0.62059333 0.9538985  0.68517564]
 [0.0853148  0.46984092 0.55949487 0.23808503]]
Вектор:
[0.45271017 0.65652644 0.05606482 0.48848289]
Добуток вектора на матрицю:
[0.47890401 0.99248423 0.49475431]


In [23]:
#Завдання 11
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток вектора на матрицю.
import numpy as np
matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, size=3)
result = np.dot(vector, matrix)
print("Матриця 2x3:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nДобуток вектора на матрицю:")
print(result)



In [16]:
#Завдання 12
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів обох матриць.
import numpy as np
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
difference_matrix = matrix1 - matrix2
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nРізниця матриць:")
print(difference_matrix)


Перша матриця:
[[ 7  4  3  8]
 [ 5  6  4  9]
 [10  9  7  3]
 [ 8 10  6  6]]

Друга матриця:
[[ 6  7  2 10]
 [ 9  2  3  4]
 [10  4  4 10]
 [ 6 10  3  2]]

Різниця матриць:
[[ 1 -3  1 -2]
 [-4  4  1  5]
 [ 0  5  3 -7]
 [ 2  0  3  4]]


In [17]:
#Завдання 13
#Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів.
import numpy as np
matrix1 = np.random.uniform(-1, 1, size=(3, 3))
matrix2 = np.random.uniform(-1, 1, size=(3, 3))
sum_of_matrices = matrix1 + matrix2
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nСума матриць:")
print(sum_of_matrices)


Перша матриця:
[[ 0.74116649  0.74391561 -0.88741419]
 [ 0.4383219  -0.82675349  0.4164989 ]
 [ 0.44933275 -0.07287746 -0.8765617 ]]

Друга матриця:
[[ 0.08967963  0.55146542  0.23101171]
 [ 0.92361633 -0.13166541 -0.21435711]
 [ 0.84696651  0.20743515 -0.56835609]]

Сума матриць:
[[ 0.83084612  1.29538103 -0.65640248]
 [ 1.36193823 -0.9584189   0.20214179]
 [ 1.29629926  0.1345577  -1.44491778]]


In [18]:
#Завдання 14
#Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть кількість парних елементів матриці.
import numpy as np
matrix = np.random.uniform(-10, 10, size=(9, 9))
count_even_elements = np.sum(matrix % 2 == 0)
print("Матриця 9x9:")
print(matrix)
print("\nКількість парних елементів у матриці: ", count_even_elements)


Матриця 9x9:
[[ 7.49265336  1.73394719  0.51736987 -6.40164366  7.5846974  -8.86647739
   2.46279392 -5.7695348  -2.60296074]
 [ 1.07370204  6.36011331  5.08380087 -8.45230987  8.96655051 -3.14617157
  -1.46422677 -3.28071344  7.5123562 ]
 [-4.21613069 -0.4182461   8.51374156  0.73982141  7.29402077 -1.8275633
   0.18644981 -0.2790911  -0.21611306]
 [ 3.29974414 -6.60128206 -5.82598407  3.82710931  2.35538662 -9.58583103
   5.9692999  -1.71062691 -3.9060812 ]
 [ 6.66796931  5.41680076  5.63090653 -6.92582795 -2.61878253 -8.98855769
   7.81341799  4.82831899 -6.65016748]
 [-6.03504629  1.08715632 -4.06498203  8.48280545  0.78435318  3.17346547
   1.05990984  0.33725919 -1.25374753]
 [-0.40057849 -9.08257263 -3.44104866 -8.67223661 -4.74030177 -6.95983272
   4.25205161  8.70105014 -0.45208806]
 [ 1.7374717  -7.3534684   0.75894091 -0.58807624  5.50208851  7.63610017
   9.69357617  9.31484276 -4.72246746]
 [-9.77018174  3.08305802  6.73922098  7.73135269  9.68657062  1.14494425
   1.45729

In [19]:
#Завдання 15
#Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить середнє геометричне значення елементів кожного рядка матриці.
import numpy as np
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))
geometric_means = np.prod(matrix, axis=1) ** (1/5)
geometric_means_column = geometric_means.reshape(5, 1)
print("Матриця 5x5:")
print(matrix)
print("\nСереднє геометричне для кожного рядка:")
print(geometric_means_column)



Матриця 5x5:
[[ 2.12734886e-01 -2.87325053e-01 -2.13569983e-01 -3.14126160e-01
  -3.72340339e-02]
 [-5.61044728e-02 -5.57093777e-02 -4.47668274e-01 -1.27032168e-01
   3.18878840e-01]
 [ 6.33918760e-02  4.42932206e-01  1.14049938e-01 -6.15720810e-02
   3.56986242e-01]
 [-4.59003466e-01 -4.54643474e-02  1.20977774e-01  3.08670467e-01
   2.18897475e-01]
 [-3.99578523e-01 -7.69364399e-05  2.20530283e-01  1.23557878e-01
  -5.28062140e-02]]

Середнє геометричне для кожного рядка:
[[0.17248817]
 [0.1414765 ]
 [       nan]
 [0.17635414]
 [       nan]]


<ipython-input-19-a9ce787bc2e6>:5: RuntimeWarning: invalid value encountered in power
  geometric_means = np.prod(matrix, axis=1) ** (1/5)
